version: '3'
services:
  redis:
    image: "redis"
    restart: always
    environment:
      - TZ=Asia/Shanghai
  mysql:
    build: ./mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=SZheScan
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]

  web:
    build: .
    ports:
     - "5000:5000"
    links:
     - mysql:mysql
     - redis:redis
    depends_on:
     - mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
  rq:
    build: .
    depends_on:
      - redis
      - web
    command: "rq worker -c rqsettings"
    restart: always
    environment:
      - TZ=Asia/Shanghai
