"""empty message

Revision ID: 115d7c0254f8
Revises: 
Create Date: 2020-05-12 21:20:02.402463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '115d7c0254f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buglist', sa.Column('buggrade', sa.String(length=7), nullable=False))
    op.add_column('buglist', sa.Column('bugname', sa.String(length=100), nullable=False))
    op.drop_column('buglist', 'bugtypeid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buglist', sa.Column('bugtypeid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('buglist', 'bugname')
    op.drop_column('buglist', 'buggrade')
    # ### end Alembic commands ###
