"""empty message

Revision ID: 1360380eb154
Revises: 1437284a1ad1
Create Date: 2020-05-04 22:56:58.566877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1360380eb154'
down_revision = '1437284a1ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baseinfo', 'senmessage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseinfo', sa.Column('senmessage', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
