"""empty message

Revision ID: 189af24437db
Revises: f332244bdfc3
Create Date: 2020-05-11 18:15:11.395788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189af24437db'
down_revision = 'f332244bdfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poc', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poc', 'name')
    # ### end Alembic commands ###
