"""empty message

Revision ID: 27d91a31d427
Revises: cfd047dc4c3c
Create Date: 2022-02-16 13:53:00.088220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27d91a31d427'
down_revision = 'cfd047dc4c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanTask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tid', sa.String(length=128), nullable=False),
    sa.Column('starttime', sa.String(length=30), nullable=False),
    sa.Column('endtime', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('task', sa.Column('key', sa.String(length=24), nullable=False))
    op.drop_column('task', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('state', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('task', 'key')
    op.drop_column('task', 'name')
    op.drop_table('scanTask')
    # ### end Alembic commands ###
