"""empty message

Revision ID: 4c2c7a5ea6ad
Revises: 
Create Date: 2022-01-05 16:09:16.907784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2c7a5ea6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boolcheck', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('responseheader', sa.Text(), nullable=False),
    sa.Column('Server', sa.Text(), nullable=True),
    sa.Column('portserver', sa.Text(), nullable=True),
    sa.Column('sendir', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buglist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oldurl', sa.String(length=50), nullable=True),
    sa.Column('bugurl', sa.String(length=200), nullable=True),
    sa.Column('bugname', sa.String(length=100), nullable=False),
    sa.Column('buggrade', sa.String(length=7), nullable=False),
    sa.Column('payload', sa.String(length=200), nullable=True),
    sa.Column('bugdetail', sa.Text(length=16777216), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domaininfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baseinfoid', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.Text(), nullable=True),
    sa.Column('whois', sa.Text(), nullable=True),
    sa.Column('bindingip', sa.Text(), nullable=True),
    sa.Column('sitestation', sa.Text(), nullable=True),
    sa.Column('recordinfo', sa.Text(length=16777216), nullable=True),
    sa.Column('domainaddr', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitationcode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baseinfoid', sa.Integer(), nullable=False),
    sa.Column('bindingdomain', sa.Text(), nullable=True),
    sa.Column('sitestation', sa.Text(), nullable=True),
    sa.Column('CMessage', sa.Text(), nullable=False),
    sa.Column('ipaddr', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('boolcheck', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('blog', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('pw_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('profile')
    op.drop_table('poc')
    op.drop_table('log')
    op.drop_table('ipinfo')
    op.drop_table('invitationcode')
    op.drop_table('domaininfo')
    op.drop_table('buglist')
    op.drop_table('baseinfo')
    # ### end Alembic commands ###
