"""empty message

Revision ID: 5ef48274b2d7
Revises: 
Create Date: 2020-05-15 10:34:28.757309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ef48274b2d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buglist', sa.Column('bugname', sa.String(length=100), nullable=False))
    op.drop_column('buglist', 'bugtypeid')
    op.add_column('poc', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('pw_hash', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('user', 'pw_hash')
    op.drop_column('poc', 'name')
    op.add_column('buglist', sa.Column('bugtypeid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('buglist', 'bugname')
    # ### end Alembic commands ###
