"""empty message

Revision ID: 6d5a352a7684
Revises: 
Create Date: 2020-05-11 20:40:29.654941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5a352a7684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poc')
    # ### end Alembic commands ###
