"""empty message

Revision ID: 823c021e9257
Revises: 
Create Date: 2020-05-09 11:19:17.661728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823c021e9257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitationcode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitationcode')
    # ### end Alembic commands ###
