"""empty message

Revision ID: 84b12cc2eff3
Revises: 1815e51e2cc6
Create Date: 2022-02-18 22:44:23.697094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84b12cc2eff3'
down_revision = '1815e51e2cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VulList',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('pocname', sa.String(length=128), nullable=False),
    sa.Column('references', sa.String(length=128), nullable=False),
    sa.Column('created', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanTask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.String(length=128), nullable=False),
    sa.Column('tid', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('starttime', sa.String(length=30), nullable=False),
    sa.Column('endtime', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scantask')
    op.drop_table('vullist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vullist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('pocname', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('pocDesc', mysql.TEXT(), nullable=True),
    sa.Column('references', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('scantask',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('tid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('starttime', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('endtime', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('scanTask')
    op.drop_table('VulList')
    # ### end Alembic commands ###
