"""empty message

Revision ID: 8860fa8d55de
Revises: 
Create Date: 2020-05-02 18:04:59.635407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8860fa8d55de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buglist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oldurl', sa.String(length=50), nullable=True),
    sa.Column('bugurl', sa.String(length=50), nullable=True),
    sa.Column('bugtype', sa.Text(), nullable=True),
    sa.Column('buggrade', sa.String(length=10), nullable=True),
    sa.Column('bugdetail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domaininfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subdomain', sa.Text(), nullable=True),
    sa.Column('whois', sa.Text(), nullable=True),
    sa.Column('bindingip', sa.Text(), nullable=True),
    sa.Column('sitestation', sa.Text(), nullable=True),
    sa.Column('recordinfo', sa.String(length=100), nullable=True),
    sa.Column('domainaddr', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highbug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bindingdomain', sa.Text(), nullable=True),
    sa.Column('sitestation', sa.Text(), nullable=True),
    sa.Column('CMessage', sa.Text(), nullable=False),
    sa.Column('ipaddr', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lowbug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediumbug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seriousbug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seriousbug')
    op.drop_table('mediumbug')
    op.drop_table('lowbug')
    op.drop_table('ipinfo')
    op.drop_table('highbug')
    op.drop_table('domaininfo')
    op.drop_table('buglist')
    # ### end Alembic commands ###
