"""empty message

Revision ID: b81c5a12eefa
Revises: 
Create Date: 2020-05-09 11:21:19.925716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b81c5a12eefa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boolcheck', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('responseheader', sa.Text(), nullable=False),
    sa.Column('Server', sa.String(length=100), nullable=True),
    sa.Column('portserver', sa.Text(), nullable=True),
    sa.Column('sendir', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buglist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oldurl', sa.String(length=50), nullable=True),
    sa.Column('bugurl', sa.String(length=50), nullable=True),
    sa.Column('bugtypeid', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(length=100), nullable=True),
    sa.Column('bugdetail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bugtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bugtype', sa.String(length=50), nullable=False),
    sa.Column('buggradeid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domaininfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baseinfoid', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.Text(), nullable=True),
    sa.Column('whois', sa.Text(), nullable=True),
    sa.Column('bindingip', sa.Text(), nullable=True),
    sa.Column('sitestation', sa.Text(), nullable=True),
    sa.Column('recordinfo', sa.Text(), nullable=True),
    sa.Column('domainaddr', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitationcode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baseinfoid', sa.Integer(), nullable=False),
    sa.Column('bindingdomain', sa.Text(), nullable=True),
    sa.Column('sitestation', sa.Text(), nullable=True),
    sa.Column('CMessage', sa.Text(), nullable=False),
    sa.Column('ipaddr', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bug')
    op.drop_column('log', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.create_table('bug',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Server', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('bugdetail', mysql.TEXT(), nullable=False),
    sa.Column('response', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('ipinfo')
    op.drop_table('invitationcode')
    op.drop_table('domaininfo')
    op.drop_table('bugtype')
    op.drop_table('buglist')
    op.drop_table('baseinfo')
    # ### end Alembic commands ###
