"""empty message

Revision ID: cfd047dc4c3c
Revises: 4c2c7a5ea6ad
Create Date: 2022-02-16 13:07:36.307484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfd047dc4c3c'
down_revision = '4c2c7a5ea6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tid', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('starttime', sa.String(length=30), nullable=False),
    sa.Column('endtime', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('baseinfo')
    op.drop_table('ipinfo')
    op.drop_table('domaininfo')
    op.drop_table('buglist')
    op.drop_table('invitationcode')
    op.drop_table('profile')
    op.drop_table('poc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poc',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('rule', mysql.TEXT(), nullable=True),
    sa.Column('expression', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('profile',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('blog', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('signature', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('invitationcode',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('buglist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('oldurl', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bugurl', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bugname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('buggrade', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('payload', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bugdetail', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('domaininfo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('baseinfoid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subdomain', mysql.TEXT(), nullable=True),
    sa.Column('whois', mysql.TEXT(), nullable=True),
    sa.Column('bindingip', mysql.TEXT(), nullable=True),
    sa.Column('sitestation', mysql.TEXT(), nullable=True),
    sa.Column('recordinfo', mysql.LONGTEXT(), nullable=True),
    sa.Column('domainaddr', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('ipinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('baseinfoid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bindingdomain', mysql.TEXT(), nullable=True),
    sa.Column('sitestation', mysql.TEXT(), nullable=True),
    sa.Column('CMessage', mysql.TEXT(), nullable=False),
    sa.Column('ipaddr', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('baseinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('boolcheck', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('responseheader', mysql.TEXT(), nullable=False),
    sa.Column('Server', mysql.TEXT(), nullable=True),
    sa.Column('portserver', mysql.TEXT(), nullable=True),
    sa.Column('sendir', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('task')
    # ### end Alembic commands ###
