"""empty message

Revision ID: f332244bdfc3
Revises: 
Create Date: 2020-05-11 17:50:51.396727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f332244bdfc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poc')
    # ### end Alembic commands ###
