"""empty message

Revision ID: f810509fd6ce
Revises: 4e694382f616
Create Date: 2020-05-06 14:07:33.872530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f810509fd6ce'
down_revision = '4e694382f616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buglist', sa.Column('bugtypeid', sa.Integer(), nullable=False))
    op.add_column('bugtype', sa.Column('bugtype', sa.String(length=50), nullable=False))
    op.drop_column('bugtype', 'buglistid')
    op.drop_column('bugtype', 'bugtypeid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugtype', sa.Column('bugtypeid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bugtype', sa.Column('buglistid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('bugtype', 'bugtype')
    op.drop_column('buglist', 'bugtypeid')
    # ### end Alembic commands ###
