"""empty message

Revision ID: fd29b1639463
Revises: 
Create Date: 2020-05-05 23:19:32.638734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd29b1639463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buglist', sa.Column('payload', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buglist', 'payload')
    # ### end Alembic commands ###
